name: Python build


on:
 push:
   branches:
     - main
 workflow_dispatch:      

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: buildstep1
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: py build installing dependences     
      run: pip install -r requirements.txt
    - name: executing test
      run: pytest
