name: Python build


on:
 push:
   branches:
     - main
 workflow_dispatch:      

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: buildstep1
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: py build installing dependences     
      run: pip install -r requirements.txt
    - name: executing test
      run: pytest
      continue-on-error: true
    - name: chceking
      run: echo testing after error execution
    - name: docker installation
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - name: build docker image
    - run: |  
        set -x

        docker version
        docker build -t mydockerimage .
