name: Python build


on:
 push:
   branches:
     - main
 workflow_dispatch:      

jobs:
  build-and-test:
    runs-on: runnersiva1
    steps:
    - name: login as root user
      run: sudo su -  
    - name: buildstep1
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: py build installing dependences     
      run: pip install -r requirements.txt
    - name: executing test
      run: pytest
      continue-on-error: true
    - name: checking
      run: echo testing after error execution
        #- name: docker installation
      # uses: docker-practice/actions-setup-docker@master
      #timeout-minutes: 12
    - name: build docker image
      run: |  
        set -x

        docker version
        docker build -t sivaastra2023/mydockerimage1 .

    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  
    - name: docker push 
      run: docker push sivaastra2023/mydockerimage1
